{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim ) (eq "-" .Values.externalDatabase.type ) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-pvc
  labels: 
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  {{- if not (empty .Values.persistence.accessMode) }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  resource:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClassName }}
  storageclassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
{{- end -}}