---
## @section "Common parameters"
## 
image:
  ## @param image.repository
  ##
  repository: vaultwarden/server
  ## @param image.pullpolicy 
  ##
  pullPolicy: IfNotPresent
  ## @param image.tag [string] Overrides the image tag whose default is the chart appVersion.
  ##
  tag: "1.25.2"
  ## @param image.digist
  ##
  digist: "" //todo::
## @param securityContext
##  capabilities:
##    drop:
##    - ALL
##  readOnlyRootFilesystem: true
##  runAsNonRoot: true
##  runAsUser: 1000
##
securityContext: {}
## [Kubernetes autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) 
## @param autoscaling.enabled Enable horizontal POD autoscaling
## @param autoscaling.minReplicas Minimum number of replicas
## @param autoscaling.maxReplicas Maximum number of replicas
## @param autoscaling.targetCPU Target CPU utilization percentage
## @param autoscaling.targetMemory Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## @skip podAnnotations
##
podAnnotations: {}
## @skip podSecurityContext
## fsGroup: 2000
##
podSecurityContext: {}
## @skip imagePullSecrets
##
imagePullSecrets: []
## @skip nameOverride
##
nameOverride: ""
## @skip fullnameOverride
##
fullnameOverride: ""
## @skip replicaCount
##
replicaCount: 1
## @skip nodeSelector
##
nodeSelector: {}
## @skip tolerations
##
tolerations: []
## @skip affinity
##
affinity: {}
## @section "Service realted parameter"
##
service:
  ## @param service.type [string] Kubernetes service type
  ##
  type: ClusterIP
  ## @param service.ports [array] List of service ports
  ##
  port:
    - name: websocket
      protocol: TCP
      targetPort: 3012
      port: 3012
    - name: http
      protocol: TCP
      targetPort: 8080
      port: 80
  ## @param service.clusterIP Service cluster IP
  ## For example: "None"
  ##
  clusterIP: ""
  ## @param service.sessionAffinity Service session afffinity
  ##
  sessionAffinity: None
  ## @param service.sessionAffinityConfig Additional settings for the sessionAffinity
  ## sessionAffinityConfig:
  ##   clientIP:
  ##     timeoutSeconds: 180
  ## 
  sessionAffinityConfig: {}
  ## @param service.externalTrafficPolicy [array] Service external traffic policy 
  ##
  externalTrafficPolicy: []

## @section "serviceAccount related parameter"
##
serviceAccount:
  ## @param serviceAccount.create 
  ## Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## @section "Ingress related parameters"
##
##
ingress:
  ## @param ingress.enabled turn on/off ingress of the chart at all
  ##
  enabled: false
  ## @param ingress.className 
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## @skip podAnnotations
##
podAnnotations: {}
## @skip podSecurityContext
## fsGroup: 2000
##
podSecurityContext: {}

