---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  {{- if .Values.adminToken }}
  ADMIN_TOKEN: {{ .Values.adminToken | quote }}
  {{- end }}
  DATA_FOLDER: {{ .Values.storage.dataFolder | quote }}
  {{- if ne "default" .Values.database.type }}
  {{- if .Values.database.overrideUri }}
  DATABASE_URL: {{ .Values.database.overrideUri }}
  {{- else }}
  DATABASE_URL: {{ include "dbUri" . | quote }}
  {{- end }}
  {{- end }}
  DISABLE_ADMIN_TOKEN: {{ .Values.disableAdminToken | quote }}
  DOMAIN: {{ .Values.domain | quote }}
  INVITATIONS_ALLOWED: {{ .Values.invitationsAllowed | quote }}
  {{- if .Values.rocket.limits }}
  ROCKET_LIMITS: {{ .Values.rocket.limits | quote }}
  {{- end }}
  {{- if .Values.rocket.tls }}
  ROCKET_TLS: {{ .Values.rocket.tls | quote }}
  {{- end }}
  {{- if .Values.rocket.workers }}
  ROCKET_WORKERS: {{ .Values.rocket.workers | quote }}
  {{- end }}
  SIGNUPS_ALLOWED: {{ .Values.signups.allowed | quote }}
  {{- if .Values.signups.domainWhitelist }}
  SIGNUPS_DOMAINS_WHITELIST: {{ .Values.signups.domainWhitelist | quote }}
  {{- end }}
  SHOW_PASSWORD_HINT: {{ .Values.showPasswordHint | quote }}
  {{- if and .Values.smtp.urn .Values.smtp.from }}
  SMTP_HOST: {{ .Values.smtp.urn | quote }}
  SMTP_SECURITY: {{ .Values.smtp.security | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  SMTP_FROM: {{ .Values.smtp.from | quote }}
  {{- end }}
  WEB_VAULT_ENABLED: {{ default "true" .Values.webVaultEnabled | quote }}
  WEBSOCKET_ENABLED: {{ .Values.websocketEnabled | quote }}
  {{- if and .Values.yubikey.clientID .Values.yubikey.secretKey }}
  YUBICO_CLIENT_ID: {{ .Values.yubikey.clientID | quote }}
  YUBICO_SECRET_KEY: {{ .Values.yubikey.secretKey | quote }}
  {{- if .Values.yubikey.server }}
  YUBICO_SERVER: {{ .Values.yubikey.server | quote }}
  {{- end }}
  {{- end }}