---
name: "publish the Helm Chart"
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '!**.md'
jobs:
  publish-helm-chart:
    name: "Publish Helm Chart"
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - run: echo "Checkout branch"
      - name: "checkout project code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Helm package"
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"